# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicts', '0002_article_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('action', models.BooleanField(choices=[(True, 'Add'), (False, 'Retract')], default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionary',
            name='structure',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicts.Article'),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
