# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0003_auto_20160513_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='lang_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lang_in', to='dicts.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionary',
            name='lang_out',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lang_out', to='dicts.Language'),
            preserve_default=False,
        ),
    ]
