# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0004_auto_20160513_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lang_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_out', to='dicts.Language'),
        ),
    ]
